---
all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/oficina_oci
  children:
    docker_hosts:
      children:
        bots: {}
        backend: {}
    bots:
      hosts:
        bots-01:
          ansible_host: BOTS_PUBLIC_IP_OR_DNS
          private_ip: 10.0.1.11
    backend:
      hosts:
        backend-01:
          ansible_host: BACKEND_PUBLIC_IP_OR_DNS
          private_ip: 10.0.1.10
