/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardBirthdaysRouteImport } from './routes/dashboard.birthdays'
import { Route as DashboardEconomyActionCostsRouteImport } from './routes/dashboard.economy.action-costs'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBirthdaysRoute = DashboardBirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEconomyActionCostsRoute =
  DashboardEconomyActionCostsRouteImport.update({
    id: '/economy/action-costs',
    path: '/economy/action-costs',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/economy/action-costs': typeof DashboardEconomyActionCostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/economy/action-costs': typeof DashboardEconomyActionCostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/birthdays': typeof DashboardBirthdaysRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/economy/action-costs': typeof DashboardEconomyActionCostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/birthdays'
    | '/dashboard/login'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/dashboard/economy/action-costs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/birthdays'
    | '/dashboard/login'
    | '/dashboard/tickets'
    | '/dashboard'
    | '/dashboard/economy/action-costs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/birthdays'
    | '/dashboard/login'
    | '/dashboard/tickets'
    | '/dashboard/'
    | '/dashboard/economy/action-costs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/birthdays': {
      id: '/dashboard/birthdays'
      path: '/birthdays'
      fullPath: '/dashboard/birthdays'
      preLoaderRoute: typeof DashboardBirthdaysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/economy/action-costs': {
      id: '/dashboard/economy/action-costs'
      path: '/economy/action-costs'
      fullPath: '/dashboard/economy/action-costs'
      preLoaderRoute: typeof DashboardEconomyActionCostsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBirthdaysRoute: typeof DashboardBirthdaysRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEconomyActionCostsRoute: typeof DashboardEconomyActionCostsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBirthdaysRoute: DashboardBirthdaysRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEconomyActionCostsRoute: DashboardEconomyActionCostsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
